config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homepage#index'
  resources :homepage, only: [:index]
  resources :users, only: [:show, :edit, :update], :path => 'my_profile' do
    resources :avatars, only: [:show, :edit, :update]
  end
  resources :real_estates do
    resources :chatroom, only: [:index, :create]
  end
  resources :charges, only: [:new, :create], :path => 'checkout'
  resources :house_coins, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :destroy], :path => 'my_cart'

  namespace :admin do
    resources :real_estates
  end

  resources :subscribers, only: [:create]

  # static pages
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy_policy', to: 'static_pages#privacy_policy', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar

  has_many :house_coins
  has_many :real_estates
  has_many :charges
  has_many :orders ,through: :charges
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #TODO reactivate mailers
  after_create :welcome_send

  validates :email, format: {
    with: /\A([\w\._-]+)@([\w-]+)\.(\w+)\z/,
    message: 'not valid'
  }

  private
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :verify_identity

  def show
    @user = find_user
  end

  def edit
    @user = find_user
  end

  def update
    @user = find_user
    unless params[:avatar].nil?
      @user.avatar.attach(params[:avatar])
    else
      @user.avatar.purge
    end

    if @user.update(permited_params)
      flash[:notice] = "User profile updated!"
      redirect_to user_path(@user)
    else
      flash.now[:notice] = "Ouppps !"
      render :edit
    end
  end

  private

  def verify_identity
    @user = find_user
    if @user != current_user
      flash[:notice] = "This is not your profile"
      redirect_to root_path
    end
  end

  def find_user
    User.find(params[:id])
  end

  def permited_params
    params.permit(:username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_house_coins.html.erb
<%current_user.charges.each_with_index do | charge, i |%>
    <h4 class="mt-3">Order n°<%= i + 1 %></h4>
    <div class="list-group-item">

        <%unique_items = []%>
        <% Order.find_by(id: charge.order_id).house_coins.each do | item | %>
            <% if !unique_items.map{ | c | c.real_estate_id }.include?(item.real_estate_id) %>
                <% unique_items << item %>
            <% end %>
        <% end %>

        <% unique_items.each do | hc | %>
            <% real = RealEstate.find_by(id: hc.real_estate_id) %>
            <% quantity = HouseCoin.where("real_estate_id = ? AND user_id = ?", real.id, current_user.id) %>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <h5> You possess <%= quantity.length %> of this property <%= real.original_house_coin_number %> HouseCoins.</h5>
                    <p> Total value <%=hc.coin_price * quantity.length%> €</p>
                </li>
                    <%if real.pictures.present?%>
                        <li class="list-group-item">
                            <%=image_tag real.pictures[0], alt: real.name, style: "width: 20rem;"%>
                        </li>
                    <%else%>
                        <li class="list-group-item">
                            <%=image_tag real.image_urls, alt: real.name, style: "width: 20rem;"%>
                        </li>
                    <%end%>
                <li class="list-group-item">
                    <h5>Name</h5>
                    <div>
                        <%= link_to real.name, real_estate_path(real.id), class: 'd-block'%>
                        <%= link_to 'Chatroom', real_estate_chatroom_index_path(real.id), class: 'btn btn-primary mt-3' %>
                    </div>
                </li>
                <li class="list-group-item">
                    <h5>Address</h5>
                    <p><%=real.adress%></p>
                </li>
                <li class="list-group-item">
                    <h5>Zip code</h5>
                    <p><%=real.zipcode%></p>
                </li>
            </ul>
        <%end%>
    </div>
<%end%>

app/views/users/edit.html.erb
<section class="container d-flex flex-column align-items-center my-5">
    <h1>Edit user profile</h1>
    <div class="mw-form custom-form">
        <%= form_tag(user_path(@user.id), method: :put, id: "user-profile-form", multipart: true, direct_upload: true)  do %>
            <div class="form-group mt-3">
                <%= file_field_tag :avatar, class: "form-control" %>
            </div>
            <div class="form-group mt-3">
                <%= label_tag "User name" %>
                <%= text_field_tag :username, @user.username, class: "form-control" %>
            </div>
            <div class="form-group mt-4">
                <%= submit_tag "Save", class: "btn btn-primary me-1" %>
            </div>
        <%end%>
    </div>
</section>

app/views/users/show.html.erb
<div class="container my-5" style="height: 100%;">
  <ul class="accordion accordion-flush" id="profile-accordion">

    <!-- ITEM 01 -->
    <li class="accordion-item" id="profile-accordion-item-1">
      <!-- HEADER -->
      <h1 class="accordion-header">
        <button class="accordion-button" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#flush-collapseOne" 
                aria-expanded="true" 
                aria-controls="flush-collapseOne">
          My infos
        </button>
      </h1>
      <!-- BODY -->
      <div id="flush-collapseOne" class="accordion-collapse collapse pb-3 show" aria-labelledby="profile-accordion-item-1" data-bs-parent="#profile-accordion">
        <div class="accordion-body mt-3">
          <% @avatar_data = { class: 'img-avatar float-end ms-3 mb-3', user: current_user } %>
          <%= render :partial => "shared/avatar", :object => @avatar_data %>
          <p>Username: <%= current_user.username %></p>
          <p>Email: <%= current_user.email %></p>
          <div class="buttons d-flex mt-4">
            <%= link_to 'Modify infos', edit_user_path(current_user.id), class: "btn btn-primary mr-2" %>
            <%= link_to 'Modify registration', edit_user_registration_path(current_user.id), class: "btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    </li>

    <!-- ITEM 02 -->
    <li class="accordion-item" id="profile-accordion-item-2">
      <!-- HEADER -->
      <h1 class="accordion-header">
        <button class="accordion-button collapsed" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#flush-collapseTwo" 
                aria-expanded="false" 
                aria-controls="flush-collapseTwo">
          My HouseCoins
        </button>
      </h1>
      <!-- BODY -->
      <div id="flush-collapseTwo" 
            class="accordion-collapse collapse pb-3" 
            aria-labelledby="profile-accordion-item-2" 
            data-bs-parent="#profile-accordion">
        <div class="accordion-body">
          <%= render 'user_house_coins' %>
        </div>
      </div>
    </li>

    <!-- ITEM 03 -->
    <li class="accordion-item" id="profile-accordion-item-3">
      <!-- HEADER -->
      <h1 class="accordion-header">
        <button class="accordion-button collapsed" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#flush-collapseThree" 
                aria-expanded="false" 
                aria-controls="flush-collapseThree">
          My Offers
        </button>
      </h1>
      <!-- BODY -->
      <div id="flush-collapseThree" 
            class="accordion-collapse collapse pb-3" 
            aria-labelledby="profile-accordion-item-3" 
            data-bs-parent="#profile-accordion">
        <div class="accordion-body">
          <ul class="list-group">
            <%current_user.real_estates.each_with_index do | property, i |%>
            <li class="list-group-item">
              <h5>Offer n° <%=i + 1%></h5>
            </li>
            <li class="list-group-item">
              <h6><%= link_to property.name, real_estate_path(property.id)%><h6>
            </li>
            <li class="list-group-item">
              <%if property.pictures.present?%>
                <li class="list-group-item">
                  <%=image_tag property.pictures[0], alt: property.name, style: "width: 20rem;" %>
                </li>
              <%else%>
                <li class="list-group-item">
                  <%= image_tag property.image_urls, alt: property.name, style: "width: 20rem;" %>
                </li>
              <%end%>
            </li>
            <li class="list-group-item">
              <h5>HouseCoins left</h5>
              <p><%= property.current_house_coin_number %> / <%= property.original_house_coin_number %></p>
            </li>
            <li class="list-group-item">
              <% if !property.validated? %>
                <%= link_to 'Modify your offer', edit_real_estate_path(property.id), class: "btn btn-warning" %>
              <%end%>
            </li>
            <%end%>
          </ul>
        </div>
      </div>
    </li>

  </ul>
</div>