config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homepage#index'
  resources :homepage, only: [:index]
  resources :users, only: [:show, :edit, :update], :path => 'my_profile' do
    resources :avatars, only: [:show, :edit, :update]
  end
  resources :real_estates do
    resources :chatroom, only: [:index, :create]
  end
  resources :charges, only: [:new, :create], :path => 'checkout'
  resources :house_coins, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :destroy], :path => 'my_cart'

  namespace :admin do
    resources :real_estates
  end

  resources :subscribers, only: [:create]

  # static pages
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy_policy', to: 'static_pages#privacy_policy', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
  belongs_to :order

  after_create :buyer_charge_confirmation_mail

  private

  def buyer_charge_confirmation_mail
    UserMailer.buyer_charge_confirmation(self.user_id, self.order_id).deliver_now
  end
end

app/models/house_coin.rb
class HouseCoin < ApplicationRecord
  belongs_to :order
  belongs_to :real_estate
  belongs_to :user
  
  validate :sufficient_house_coin_num?, on: :create


  def sufficient_house_coin_num?
    num = HouseCoin.where(real_estate_id:self.real_estate_id).length
    errors.add(:id) unless 
      num < self.real_estate.current_house_coin_number
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :real_estate
  validates :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :house_coins

  def order_total
    total = 0
    self.house_coins.each do | hc |
      total += hc.coin_price
    end
    return total.to_i 
  end

  private
  def buyer_housecoin
    AdminMailer.buyer_housecoin(self.user_id, self.order_id).deliver_now
  end
end

app/models/real_estate.rb
class RealEstate < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many_attached :pictures

  belongs_to :user
  has_many :house_coins
  has_many :real_estates

  validates :name, presence: true
  validates :price, presence: true
  validates :adress ,presence: true
  validates :zipcode ,presence: true
  validates :city ,presence: true

  #TODO reactivate mailers
  after_update :offer_validation
  after_create :admin_offer_creation_mail, :original_coin_number

  def thumbnail input
    return self.pictures[input].variant(resize: '500x500').processed
  end

  def coin_price
    coin_value = ((self.price.to_f / self.original_house_coin_number)*100)/100 # The returned value must be in cents
  end

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{adress} ,#{zipcode}, #{city}"
  end

  private

  def original_coin_number
    if self.price <= 100000
    house_coins_num = 10
    elsif self.price > 100000 && self.price < 500000
    house_coins_num = 20
    elsif self.price >= 500000 && self.price < 1000000
    house_coins_num = 30
    elsif self.price >= 1000000
    house_coins_num = 40
    end
    self.update(original_house_coin_number: house_coins_num)
    self.update(current_house_coin_number: house_coins_num)
  end

  def admin_offer_creation_mail
    AdminMailer.admin_offer_creation(self).deliver_now
  end

  def offer_validation
    UserMailer.offer_validation(self.user_id).deliver_now
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    validates :email, presence: true
    validates :email, format: {
        with: /\A([\w\._-]+)@([\w-]+)\.(\w+)\z/,
        message: 'not valid'
        }

    after_create :subscriber_send

    def subscriber_send
        SubscriberMailer.subscriber_newsletter(self).deliver_now 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar

  has_many :house_coins
  has_many :real_estates
  has_many :charges
  has_many :orders ,through: :charges
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #TODO reactivate mailers
  after_create :welcome_send

  validates :email, format: {
    with: /\A([\w\._-]+)@([\w-]+)\.(\w+)\z/,
    message: 'not valid'
  }

  private
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @house_coins = current_order.house_coins
    end

    def destroy
        @flash = "Cart emptied!"
        @order = Order.find(params[:id]) 
        @order.house_coins.each do | hc |
            hc.destroy
        end

        respond_to do |format|
            format.html do 
                flash[:notice] = @flash
                redirect_to root_path
            end

            format.js do
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :verify_identity

  def show
    @user = find_user
  end

  def edit
    @user = find_user
  end

  def update
    @user = find_user
    unless params[:avatar].nil?
      @user.avatar.attach(params[:avatar])
    else
      @user.avatar.purge
    end

    if @user.update(permited_params)
      flash[:notice] = "User profile updated!"
      redirect_to user_path(@user)
    else
      flash.now[:notice] = "Ouppps !"
      render :edit
    end
  end

  private

  def verify_identity
    @user = find_user
    if @user != current_user
      flash[:notice] = "This is not your profile"
      redirect_to root_path
    end
  end

  def find_user
    User.find(params[:id])
  end

  def permited_params
    params.permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
    def total_charge(order)
        unless order.house_coins.length == 0
            total = 0 
            order.house_coins.each do |order_item|
                total += order_item.coin_price 
            end
            return total
        end
    end

    def update_products(order)
        order.house_coins.each do | hc |
            real_estate = RealEstate.find(hc.real_estate_id)
            estate_coin_num = real_estate.current_house_coin_number - 1
            real_estate.update(current_house_coin_number: estate_coin_num)
            hc.update(user: current_user)
        end
    end
    
    def is_available_to_buy?
        houses=current_order.house_coins.map{|u| u.real_estate}
        houses.each do |house| 
            if house.current_house_coin_number + houses.count(house) > house.original_house_coin_number
                return false
            end
        end
    end
end

app/helpers/chatroom_helper.rb
module ChatroomHelper

  def find_investors(real_estate)
    sql="select distinct user_id 
      from house_coins H 
      where H.real_estate_id=#{real_estate.id}"
    records_array = ActiveRecord::Base.connection.execute(sql)
    return records_array   
  end
  def find_investors_messages(real_estate)
    sql = "select distinct * from messages where messages.real_estate_id=#{real_estate.id}
            order by created_at";
    records_array = ActiveRecord::Base.connection.execute(sql)
    return records_array
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/house_coins_helper.rb
module HouseCoinsHelper
    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/real_estates_helper.rb
module RealEstatesHelper
  def is_available?(real_estate)
    if real_estate.current_house_coin_number <= 0
      return false
    end
    return true
  end

  def latest_validated
    RealEstate.where(validated?: true)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_avatar.html.erb
<% if @avatar_data[:user].avatar.attached? %>
    <%= image_tag @user.avatar, 
                    alt: 'avatar', 
                    class: @avatar_data[:class] %>
<% else %>
    <%= inline_svg_tag "profile.svg", 
                    class: 'default-avatar ' + @avatar_data[:class] %>
<% end %>

app/views/shared/_full_image.html.erb
<div class="full-image" style="background: url('<%= asset_path @dataImage[:url] %>') center center no-repeat; background-size: cover;">
    <div class="d-flex flex-column justify-content-center align-items-center h-100">
        <h1>
            <%= @dataImage[:title] %>
        </h1>
        <div class="sub-title">
            <%= @dataImage[:text] %>
        </div>
    </div>
</div>

app/views/shared/_get_housecoin.html.erb
<div class="custom-form mb-4">
    <h6>Buy HouseCoin since :</h6>
    <h5><%= @real_estate.coin_price.to_i %> € / housecoin</h5>
    <div class="d-flex mt-4">
        <%= button_to 'Get housecoin', 
                        house_coins_path, 
                        method: :post, 
                        params: { real_estate_id: @real_estate.id, coin_price: @real_estate.coin_price, user_id: @real_estate.user, order_id: current_order }, 
                        class: "btn btn-primary me-2" %>
    <% if current_user %>
        <% if current_user == @real_estate.user && !@real_estate.validated? %>
            <%= link_to 'Modify your offer', 
                        edit_real_estate_path(@real_estate.id), 
                        class: "btn btn-outline-warning me-2" %>
        <% end %>
        <% if current_user.is_admin? && !@real_estate.validated? %>
            <%= button_to 'Validate offer', 
                        admin_real_estate_path(@real_estate.id), 
                        method: :put, 
                        params: { validated?: true }, 
                        class: "btn btn-outline-primary" %>
        <% end %>
    <% end %>
    </div>
</div>

app/views/shared/_house_coin_modal_xl.html.erb
<div class="modal fade" id="realEstatePictureModal" tabindex="-1" aria-labelledby="realEstatePictureModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="realEstatePictureModalLabel"><%= @real_estate.name %></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            
            </div>
        </div>
    </div>
</div>

app/views/shared/_newsletter.html.erb
<ul class="newsletter-block mt-auto">
    <div class="container d-flex">
        <li class="col-12 col-sm-12 col-md-4">
            <%= inline_svg_tag "plane_newsletter.svg", class: 'picto_newsletter' %>
        </li>
        <li class="col-12 col-sm-12 col-md-8">
            <div class="d-flex flex-column">
                <h3 class="title-news mb-2"><strong>Subscribe to newsletter</strong></h3>
                <p class="text-news">Get the latest advices and interesting offers and real estate</p>
                <div class="mw-form">
                    <% if cookies[:saved_subscriber] %>
                        <p>Thanks for signing up!</p>
                    <% else %>
                        <%= form_for (Subscriber.new) do |f| %>
                        <div class="d-flex form-group mt-3">
                            <%= f.text_field :email, placeholder: "Enter your email", class: "form-control me-2" %>
                            <%= submit_tag "Subscribe", class: "btn btn-outline-primary" %>
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </li>
    </div>
</ul>

app/views/shared/_picto_presentation.html.erb
<div class="row my-5">
    <div class="col-4 d-flex">
        <div class="icon flex-shrink-0 me-3">
            <%= inline_svg_tag "type_building.svg", class: 'picto-show' %>
        </div>
        <div>
            <h6>Type</h6>
        </div>
    </div>
    <div class="col-4 d-flex">
        <div class="icon flex-shrink-0 me-3">
            <%= inline_svg_tag "area.svg", class: 'picto-show' %>        
        </div>
        <div>
            <h6>Area</h6>         
        </div>
        </div>
    <div class="col-4 d-flex">
        <div class="icon flex-shrink-0 me-3">
            <%= inline_svg_tag "localisation.svg", class: 'picto-show' %>
        </div>
        <div>
            <h6><%= @real_estate.city %></h6>
        </div>
    </div>
</div>

app/views/shared/_picture_modal_xl.html.erb
<div class="modal fade" id="realEstatePictureModal" tabindex="-1" aria-labelledby="realEstatePictureModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="realEstatePictureModalLabel"><%= @real_estate.name %></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%=image_tag @real_estate.image_urls, class: "w-100 real-estate-img", alt: ""%>
            </div>
        </div>
    </div>
</div>

app/views/shared/_picture_text.html.erb
<div class="container my-5">
    <h2>You might be interested in</h2>
    <ul class="row">
        <li class="col-12 col-sm-8">
            <img src="" alt="">
        </li>
        <li class="col-12 col-sm-4">
            <h2>About us</h2>
            <p></p>
        </li>
    </ul>
</div>

app/views/shared/_pictures_group.html.erb
<div class="cross-selling">
    <h2 id="selling">You might be interested in</h2>
    <ul class="estate-list row mt-4">
        <% @estates_latest.each do |estate| %>
            <li class="col-12 col-sm-6 col-md-3">
                <%= link_to real_estate_path(estate.id), 
                            :data => { :bs_toggle => "tooltip", :bs_placement => "bottom" }, 
                            title: estate.name do %>
                    <div class="card-image text-center">
                        <% if estate.pictures.attached? %>
                            <%= image_tag estate.pictures[0], alt: 'picture', class: 'w-auto h-100' %>
                        <% else %>
                            <%= image_tag estate.image_urls, alt: 'picture', class: 'w-auto h-100' %>
                        <% end %>
                    </div>
                <% end %>
            </li>
        <% end %>
    </ul>
</div>

app/views/shared/_property_type.html.erb
<div class="mb-2 aside-offer">
    <h5 class="aside-title">Property type</h5>
    <ul>
        <li>
            <p><strong>City :</strong>    <%= @real_estate.city %></p>
        </li>
        <li>
            <p><strong>Zipcode :</strong> <%= @real_estate.zipcode %></p>
        </li>
        <li>
            <p><strong>Address :</strong>  <%= @real_estate.adress %></p>
        </li>
        <li>
            <p><strong>Price :</strong>   <%= @real_estate.price %> €</p>
        </li>
    </ul>
</div>
<div class="button-housecoin mt-4">
    <%= link_to "Chatroom" ,real_estate_chatroom_index_path(params[:id]), class: "btn btn-primary" %>
</div>

app/views/shared/_real_estates_edit_form.html.erb
<%= form_with url: @path[:url], model: @real_estate, method: :put do |form|%>
    <div class="form-group mt-3">
        <%= form.label "Name" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Price" %>
        <%= form.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Description" %>
        <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Address" %>
        <%= form.text_field :adress, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Zipcode" %>
        <%= form.text_field :zipcode, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "City" %>
        <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group mt-4">
        <%= form.submit "Save", class: "btn btn-primary me-1" %>
    </div>
<%end%>

app/views/shared/_real_estates_new_form.html.erb
<%= form_with url: real_estates_path do |form|%>
    <div class="form-group mt-3">
        <%= form.label :pictures %>
        <%= form.file_field :pictures, multiple: true, direct_upload: true, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Name" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Price" %>
        <%= form.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Description" %>
        <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Address" %>
        <%= form.text_field :adress, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "Zipcode" %>
        <%= form.text_field :zipcode, class: "form-control" %>
    </div>
    <div class="form-group mt-3">
        <%= form.label "City" %>
        <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group mt-4">
        <%= form.submit "Save", class: "btn btn-primary me-1" %>
    </div>
<%end%>

app/views/shared/_small_carousel.html.erb
<div id="small-carousel" class="carousel slide mb-5" data-bs-ride="carousel">
    <!-- INDICATOR BUTTONS -->
    <div class="carousel-indicators">
        <% @real_estate.pictures.each.with_index do |img, index| %>
            <button type="button" 
                    data-bs-target="#small-carousel" 
                    data-bs-slide-to="<%= index %>" 
                    aria-label="Slide <%= index + 1 %>" 
                    <% if index == 0 %> aria-current="true" class="active"<% end %>></button>
        <% end %>
    </div>

    <div class="carousel-inner">
        <!-- BODY -->
        <% @real_estate.pictures.each.with_index do |img, index| %>
            <div class="carousel-item<% if index == 0 %> active<% end %>">
                <!-- Picture -->
                <div class="card-image text-center">
                    <% if @real_estate.pictures.attached? %>
                        <%= image_tag @real_estate.thumbnail(index), alt: 'picture', class: 'carousel-img'%>
                    <% elsif @real_estate.image_urls %>
                        <%= image_tag @real_estate.image_urls, alt: 'picture', class: 'carousel-img'%>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>

    <!-- PREV AND NEXT BUTTONS -->
    <button class="carousel-control-prev" 
            type="button" 
            data-bs-target="#small-carousel" 
            data-bs-slide="prev">
        <%= inline_svg_tag "chevron-left.svg", class: "chevron-carousel" %>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" 
            type="button" 
            data-bs-target="#small-carousel" 
            data-bs-slide="next">
        <%= inline_svg_tag "chevron-right.svg", class: "chevron-carousel" %>
        <span class="visually-hidden">Next</span>
    </button>
</div>