config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homepage#index'
  resources :homepage, only: [:index]
  resources :users, only: [:show, :edit, :update], :path => 'my_profile' do
    resources :avatars, only: [:show, :edit, :update]
  end
  resources :real_estates do
    resources :chatroom, only: [:index, :create]
  end
  resources :charges, only: [:new, :create], :path => 'checkout'
  resources :house_coins, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :destroy], :path => 'my_cart'

  namespace :admin do
    resources :real_estates
  end

  resources :subscribers, only: [:create]

  # static pages
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy_policy', to: 'static_pages#privacy_policy', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @house_coins = current_order.house_coins
    end

    def destroy
        @flash = "Cart emptied!"
        @order = Order.find(params[:id]) 
        @order.house_coins.each do | hc |
            hc.destroy
        end

        respond_to do |format|
            format.html do 
                flash[:notice] = @flash
                redirect_to root_path
            end

            format.js do
            end
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_modal_xl.html.erb
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cartModalLabel">My Cart</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%# MODAL CONTENT %>
                <div id="modal-content">
                    <%= render 'carts/product_list' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/carts/_product.html.erb
<!-- TABLE -->
<table class="table mt-5">
    <tbody>
        <tr>
            <th scope="col" width="120">Quantity</th>
            <td>
                <%= q = HouseCoin.where(order_id: current_order, real_estate_id: @hc.real_estate_id).length %>
            </td>
        </tr>
        <tr>
            <th scope="col">Price</th>
            <td>
                <%= (q * @hc.coin_price).to_i %> €
            </td>
        </tr>
        <tr>
            <th scope="col">For property</th>
            <td>
                <%= RealEstate.find(@hc.real_estate_id).name %>
            </td>
        </tr>
    </tbody>
</table>

<!-- BUTTONS group -->
<div class="d-flex">
    <%= button_to 'Remove one', 
                  house_coin_path(@hc.id), 
                  method: :delete, 
                  class: "btn btn-outline-danger btn-sm mr-2",
                  remote: true %>
    <%= button_to 'Add one more', 
                  house_coins_path, 
                  method: :post, 
                  params: { real_estate_id: @hc.real_estate_id, coin_price: @hc.coin_price, user_id: @hc.user_id, order_id: current_order }, 
                  class: "btn btn-outline-primary btn-sm",
                  remote: true %>
</div>

app/views/carts/_product_list.html.erb
<%# PRODUCT LIST %>
<ul>
    <%unique_items = []%>
    <%current_order.house_coins.each do | item |%>
        <% if !unique_items.map{ | c | c.real_estate_id }.include?(item.real_estate_id) %>
            <% unique_items << item %>
        <% end %>
    <% end %>
    <% unique_items.each do | hc | %> 
        <%@hc = hc%>
        <li>
            <%# PRODUCT %>
            <%= render 'carts/product', object: @hc %>
        </li>
    <% end %>
</ul>

<%# TOTAL %>
<table class="table table-light mt-5">
    <tbody>
        <tr>
            <th scope="col" width="120">Total</th>
            <td id="cart-total">
                <%= current_order.order_total %> €
            </td>
        </tr>
    </tbody>
</table>

<%# BUTTONS group %>
<% unless current_order.house_coins.length == 0 %>
    <div class="d-flex mt-3" id="cart-btns">
        <%= link_to 'Checkout', new_charge_path, class: "btn btn-primary mr-2" %>
        <%= button_to 'Clear cart', cart_path(current_order), method: :delete, class: "btn btn-danger", remote: true %>
    </div>
<% end %>

app/views/carts/destroy.js.erb
deleteElt = document.querySelector("#modal-content");
deleteElt.innerHTML = ""

badgeElt = document.querySelector("#cart-badge");
badgeElt.textContent = "0";
modalElt.insertAdjacentHTML("beforeend", "<%= j render 'carts/product_list' %>");

app/views/carts/index.html.erb
<div class="container">
  <h1>My Cart</h1>

  <ul class="list-group-flush">
    <%unique_items = []%>

    <%@house_coins.each do | item |%>
      <%if !unique_items.map{ | c | c.real_estate_id }.include?(item.real_estate_id)%>
        <%unique_items << item%>
      <%end%>
    <%end%>

    <%unique_items.each do | hc |%> 
      <%@hc = hc%>
      <li class="list-group-item">
        <%=render 'product', object: @hc%>
      </li>
    <%end%>
    <li class="list-group-item"><h5>Total</h5></li>
    <li class="list-group-item"><%=current_order.order_total%> €</li>
  </ul>
  <%unless current_order.house_coins.length == 0%>
    <div class="buttons d-flex">
      <%=link_to 'Checkout', new_charge_path, class: "btn btn-success mr-3"%>
      <%=button_to 'Clear cart', cart_path(current_order), method: :delete, class: "btn btn-danger"%>
    </div>
  <%end%>
</div>