config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homepage#index'
  resources :homepage, only: [:index]
  resources :users, only: [:show, :edit, :update], :path => 'my_profile' do
    resources :avatars, only: [:show, :edit, :update]
  end
  resources :real_estates do
    resources :chatroom, only: [:index, :create]
  end
  resources :charges, only: [:new, :create], :path => 'checkout'
  resources :house_coins, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :destroy], :path => 'my_cart'

  namespace :admin do
    resources :real_estates
  end

  resources :subscribers, only: [:create]

  # static pages
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy_policy', to: 'static_pages#privacy_policy', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/real_estate.rb
class RealEstate < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many_attached :pictures

  belongs_to :user
  has_many :house_coins
  has_many :real_estates

  validates :name, presence: true
  validates :price, presence: true
  validates :adress ,presence: true
  validates :zipcode ,presence: true
  validates :city ,presence: true

  #TODO reactivate mailers
  after_update :offer_validation
  after_create :admin_offer_creation_mail, :original_coin_number

  def thumbnail input
    return self.pictures[input].variant(resize: '500x500').processed
  end

  def coin_price
    coin_value = ((self.price.to_f / self.original_house_coin_number)*100)/100 # The returned value must be in cents
  end

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{adress} ,#{zipcode}, #{city}"
  end

  private

  def original_coin_number
    if self.price <= 100000
    house_coins_num = 10
    elsif self.price > 100000 && self.price < 500000
    house_coins_num = 20
    elsif self.price >= 500000 && self.price < 1000000
    house_coins_num = 30
    elsif self.price >= 1000000
    house_coins_num = 40
    end
    self.update(original_house_coin_number: house_coins_num)
    self.update(current_house_coin_number: house_coins_num)
  end

  def admin_offer_creation_mail
    AdminMailer.admin_offer_creation(self).deliver_now
  end

  def offer_validation
    UserMailer.offer_validation(self.user_id).deliver_now
  end
end

app/controllers/admin/real_estates_controller.rb
class Admin::RealEstatesController < ApplicationController
  before_action :user_signed_in? 
  before_action :is_admin?

  def index
    @estates = estates_all
  end

  def new
  end

  def create
    @real_estate = RealEstate.new(estate_params)
    @real_estate.user = current_user

    if @real_estate.save
      flash[:notice] = "Real estate created!"
      @real_estate.pictures.attach(params[:pictures])
      redirect_to admin_real_estates_path
    else
      flash.now[:notice] = "Ouppps !"
      render :new
    end
  end

  def show
    @real_estate = estate_find
  end

  def edit
    @real_estate = estate_find
  end

  def update
    @real_estate = estate_find

    if @real_estate.update(estate_params)
      flash[:notice] = "Real estate updated!"
      if @real_estate.validated?
        UserMailer.offer_validation(@real_estate.user_id).deliver_now
      end
      respond_to do | format |
        format.html {
          redirect_to admin_real_estates_path
        }
        format.js {}
      end
    else
      flash.now[:notice] = "Ouppps !"
      render :edit
    end
  end

  def destroy
    @real_estate = estate_find
    @real_estate.destroy
    redirect_to admin_real_estates_path
  end

  private

  def estates_all
    RealEstate.all
  end

  def estate_find
    RealEstate.friendly.find(params[:id])
  end

  def estate_params
      params.permit(
        :id,
        :name,
        :price,
        :description,
        :adress,
        :zipcode,
        :city,
        :validated?,
        pictures: []
      )
  end

  def is_admin?
    return true if current_user.is_admin?

    redirect_to root_path
  end
end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  before_action :user_signed_in?, except: [:index, :show, :new]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :estate_creator?, except: [:index, :show, :new, :create]
  before_action :estate_validated?, only: [:show]

  def index
    @estates = estates_all

    @markers = @estates.geocoded.map do |mark| {
      coordinates: [ mark.longitude, mark.latitude ],
      adress: mark.adress,
      price: mark.price,
      id: mark.id,
    }
    end
  end

  def show
    @estates_latest = latest_validated.max(4)
    @real_estate = estate_find
    @marker = {
      coordinates:
        [ @real_estate.longitude, @real_estate.latitude ],
        adress: @real_estate.adress,
        price: @real_estate.price,
        id: @real_estate.id
    }
  end

  def new
  end

  def create
    @real_estate = RealEstate.new(estate_params)
    @real_estate.user = current_user

    if @real_estate.save
      flash[:notice] = "Offer created"
      render :js => "window.location = '#{real_estates_path}'"
    else 
      flash[:error] = @real_estate.errors.full_messages 
      render :js => "window.location = '#{new_real_estate_path}'"
    end
  end

  def edit
    @real_estate = estate_find
  end

  def update
    @real_estate = estate_find

    if @real_estate.update(estate_params)
      flash[:notice] = "Real estate updated!"
      render :js => "window.location = '#{real_estates_path}'"
    else
      flash[:notice] = @real_estate.errors.full_messages 
      render :edit
      render :js => "window.location = '#{edit_real_estate_path(@real_estate.id)}'"
    end
  end

  def destroy
    @real_estate = estate_find
    @real_estate.destroy
    redirect_to root_path
  end

  private

  def estates_all
    RealEstate.all
  end

  def estate_find
    RealEstate.friendly.find(params[:id])
  end

  def estate_validated?
    unless estate_find.validated? || current_user.id == estate_find.user_id
      redirect_to root_path
    end
  end

  def estate_creator?
    unless estate_find.user == current_user
      flash[:notice] = "This is not your property!"
      redirect_to root_path
    end
  end

  def estate_params
      params.permit(
        :name,
        :price,
        :description,
        :adress,
        :zipcode,
        :city,
        pictures: []
      )
  end
end

app/helpers/admin/real_estates_helper.rb
module Admin::RealEstatesHelper
end

app/helpers/real_estates_helper.rb
module RealEstatesHelper
  def is_available?(real_estate)
    if real_estate.current_house_coin_number <= 0
      return false
    end
    return true
  end

  def latest_validated
    RealEstate.where(validated?: true)
  end
end

app/views/admin/real_estates/edit.html.erb
<section class="container d-flex flex-column align-items-center my-5">
    <h1>Edit real estate</h1>
    <div class="mw-form custom-form">
        <% @path = {data: @real_estate, url: admin_real_estate_path(@real_estate.id), method: 'put'} %>
        <%= render :partial => "shared/real_estates_edit_form", :object => @path %>
    </div>
</section>

app/views/admin/real_estates/index.html.erb
<section class="container my-5">
    <h1>Dashboard</h1>
    <div class="dashboard-table my-5">
        <div class="d-flex justify-content-between pb-2 px-2">
            <strong>Name</strong>
            <%= link_to "", new_admin_real_estate_path, 
                            class: "btn-circle btn-primary fas fa-plus",
                            :data => { :bs_toggle => "tooltip", :bs_placement => "top" },
                            title: "New estate" %>
        </div>
        <% @estates.each do |estate| %>
            <div class="row">
                <div class="col-12 col-sm-9 px-2">
                    <%= link_to estate.name, admin_real_estate_path(estate.id), class: "text-primary" %>
                </div>
                <div class="col-12 col-sm-3 px-2 d-flex justify-content-end">
                    <% if estate.validated? %>
                        <i class="primary fas fa-check ms-1 my-1"></i>
                    <% end %>
                    <% @real_estate = estate %>

                    <%= link_to "", 
                                edit_admin_real_estate_path(estate.id), 
                                class: "btn-circle btn-primary fas fa-edit ms-2 my-1",
                                :data => { :bs_toggle => "tooltip", :bs_placement => "top" },
                                title: "Edit estate" %>
                    <% if estate.house_coins.length == 0 %>
                        <%= link_to "", 
                                    admin_real_estate_path(estate.id), 
                                    method: :delete,
                                    class: "btn-circle btn-danger fas fa-trash-alt ms-1 my-1",
                                    :data => { :bs_toggle => "tooltip", :bs_placement => "top" },
                                    title: "Delete estate" %>
                    <% else %>
                        <i class="btn-circle btn-danger fas fa-trash-alt ms-1 my-1 disabled"></i>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/admin/real_estates/new.html.erb
<section class="container d-flex flex-column align-items-center my-5">
    <h1>New real estate</h1>
    <div class="mw-form custom-form">
        <% @path = {url: admin_real_estates_path, method: 'post'} %>
        <%= render :partial => "shared/real_estates_new_form", :object => @path %>
    </div>
</section>

app/views/admin/real_estates/show.html.erb
<div class="container d-flex flex-column my-5">
    <h1>
        <%= @real_estate.name %>
    </h1>
    <article class="row mt-5">
        <div class="d-flex flex-column col-12 col-sm-6 col-md-8">
            <% if @real_estate.pictures.attached? %>
                <%= render :partial => "shared/small_carousel", :object => @real_estate %>
            <% elsif @real_estate.image_urls %>
                <figure class="estate-full-figure">
                    <%= image_tag @real_estate.image_urls, alt: 'picture', class: 'estate-full-image'%>
                </figure>
            <% end %>
            <%= render :partial => "shared/picto_presentation" %>
            <%= render :partial => "shared/get_housecoin", :object => @button %>
            <%= @real_estate.description %>
            <!-- MAP -->
            <div class="mt-5">
                <%= render 'real_estates/mapbox_show' %>
            </div>
        </div>
        <div class="d-flex flex-column col-12 col-sm-6 col-md-4">
            <%= render :partial => "shared/property_type", :object => @text %>
        </div>
    </article>
</div>